# Generated by Django 6.0.6 on 2026-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Blog cover image', upload_to='blogs/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(help_text='Blog title', max_length=200)),
                ('description', models.TextField(help_text='Blog description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
