# Generated by Django 6.0.6 on 2026-07-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0003_category_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('room_category', models.CharField(blank=True, max_length=100)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bedroom_beds', models.CharField(blank=True, max_length=255)),
                ('living_room_beds', models.CharField(blank=True, max_length=255)),
                ('rating_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='rooms/main/')),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('views', models.JSONField(blank=True, default=list)),
                ('bathroom_amenities', models.JSONField(blank=True, default=list)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
