# Generated by Django 6.0.6 on 2026-07-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
