# Generated by Django 6.0.6 on 2026-07-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0005_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='max_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
