# Generated by Django 6.0.6 on 2026-07-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0008_activity_activityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('name', models.CharField(help_text='Destination name', max_length=200)),
                ('description', models.TextField(help_text='Destination description')),
                ('image', models.ImageField(help_text='Main destination image', upload_to='nearby_destinations/')),
                ('distance', models.CharField(blank=True, help_text="e.g. '5 km', '20 mins drive'", max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nearby Destination',
                'verbose_name_plural': 'Nearby Destinations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NearbyDestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nearby_destinations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ambadyestate_app.nearbydestination')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
