# Generated by Django 6.0.6 on 2026-07-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0009_nearbydestination_nearbydestinationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('name', models.CharField(help_text='Package name', max_length=200)),
                ('description', models.TextField(help_text='Package description')),
                ('image', models.ImageField(help_text='Main package image', upload_to='packages/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('duration', models.CharField(blank=True, help_text="e.g. '3 Days / 2 Nights'", max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, help_text='Activities included in this package', related_name='packages', to='ambadyestate_app.activity')),
                ('rooms', models.ManyToManyField(blank=True, help_text='Rooms included in this package', related_name='packages', to='ambadyestate_app.room')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
