# Generated by Django 6.0.6 on 2026-07-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0010_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bathroom_amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_adults',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_children',
        ),
        migrations.RemoveField(
            model_name='room',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='size_sqm',
        ),
        migrations.RemoveField(
            model_name='room',
            name='views',
        ),
    ]
