# Generated by Django 6.0.6 on 2026-07-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0011_remove_room_bathroom_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='package',
            name='inclusions',
        ),
    ]
