# Generated by Django 6.0.6 on 2026-07-07 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0012_remove_package_exclusions_remove_package_inclusions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=30)),
                ('num_guests', models.PositiveIntegerField(default=1)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='ambadyestate_app.package')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='ambadyestate_app.room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
