# Generated by Django 6.0.6 on 2026-07-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0013_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
