# Generated by Django 6.0.6 on 2026-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambadyestate_app', '0016_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
